vearch/vearch

benchs/README.md

Benchs of Vearch

---

cloud/build.sh
cloud/compile.sh
cloud/compile_env.sh
cloud/run_docker.sh
test/test_vearch.py

modify image version

---

cloud/compile.sh
cloud/env/env.sh
docs/Quickstart.md

Hi everyone. This resolves #182 and also fixes a typo in Quickstart document. And i've add git submodule download in cloud/compile.sh to make the build more automatic since `git clone` does not downloads Gamma into the engine folder.

Faiss version fix and typo in Quickstart

---

master/cluster_api.go

modify the variable name

---

docs/APILowLevel.md
ps/engine/gammacb/query.go

In the query condition, direct_search_type change to is_ brute_ search

direct_search_type change to is_brute_search

---

docs/SourceCompileDeployment.md

modify SourceCompileDeployment doc

modify SourceCompileDeployment doc

---

build/build.sh
docs/SourceCompileDeploymentZH_CN.md

One-click deployment of development environment and documentation. Easy for users to compile and deploy.

One-click deployment of development environment and documentation

---

cloud/compile.sh

otherwise, we won't have a chance to answer the question of `Do you use zfp?[y/n]`

fix compile.sh

---

build/build.sh
docs/SourceCompileDeployment.md
docs/SourceCompileDeploymentZH_CN.md

1. update gamma: put faiss 1.6.4 into third_party, user no longer have to compile faiss
2. update compile docs, remove faiss install

Users no longer need to compile faiss by themselves

---

cloud/Dockerfile

fix shortest doc chain intersection error

fix shortest doc chain intersection error

---

client/master.go
config/config.go
ps/engine/engine.go
ps/engine/gammacb/gamma.go
ps/engine/gammacb/snapshot.go
ps/storage/raftstore/store.go
ps/storage/raftstore/store_raft_snapshot.go

fix raft snapshot
1.close engine
2.remove engine data
3.trigger snapshot copy dump file
4.re build engine
5.load dump file

fix raft snapshot

---

client/master.go

update err number

---

client/client.go
proto/entity/space.go
ps/engine/gammacb/util.go
router/document/doc_parse.go

support Scalar insert and query and fix vector normalization for insert

support Scalar insert and query and fix vector normalization for insert

---

client/master.go
ps/server.go

the config.Conf().Router.RouterIPS is always null，so auto recover ps can not success;
"num := 0" should be outside.

fix auto recover ps fail because of empty RouterIPS

---

util/metrics/mserver/monitor.go

This PR fixes the calculation of fs used percent.

fix fs used percent

---

ps/engine/gammacb/snapshot.go

The last snapshot file is not closed. This PR fixes this problem.

close file after snapshot finished

---

router/document/doc_parse.go

fix: Error when inserting document include the maximum value of long type

fix: Error when inserting document include the maximum value of long type

---

go.mod
master/schedule_job.go

fix: memory and goroutine leak when doing cleanTask

fix: memory and goroutine leak when doing cleanTask

---

router/document/doc_service.go

fix:The results of _bulk_search are in the wrong order 
#570

fix:The results of _bulk_search are in the wrong order

---

internal/entity/space_test.go

add space test cases

---

sdk/integrations/langchain/vearch.py

fix:langchain remove text field index

---

internal/entity/user.go
internal/master/cluster_api.go
internal/master/cluster_service.go
internal/router/document/doc_http.go
test/test_module_user.py
test/utils/vearch_utils.py

1.no need to auth internal interface
2.check old password when update user password

feat: rbac authentication

---

internal/engine/CMakeLists.txt
internal/engine/index/impl/gpu/gamma_index_ivfpq_gpu.cc
internal/engine/index/impl/gpu/gamma_index_ivfpq_gpu.h

I have made updates to the code in an attempt to compile the GPU version. During this process, I discovered that some interfaces were outdated. This pull request includes the necessary modifications to bring these interfaces up to date.

Update GPU index impl

---

docs/DeployByDocker.md

Some adjustments to the content display and corrected a few typos.

docs: Update DeployByDocker.md: some adjustments to the content display and corrected a few typos.
